baseURL = "https://yuzuafro.github.io/yuzuafrolog/"
languageCode = "ja-jp"
title = "ゆずあふろのブログ"
copyright = "&copy; yuzuafro"
theme = "vienna"
paginate = 5

[params]
  twitter = "yuzu_afro"
  github = "yuzuafro"
  instagram = "yuzukonango"
  disqus = "yuzuafro"
  subtitle = "技術の話や趣味の話など"
